---
## Playbook for prerelease
# this playbook should be run for each release

- name: Coping artifacts
  copy:
   src: "{{item}}"
   dest: "{{hybris_install}}"
  with_items:
   - "{{hybris_repo}}/{{hybris_release_zip_name}}"

- name: Unzip hybris extensions
  command: unzip -o "{{hybris_install}}/{{hybris_release_zip_name}}" -d "{{hybris_install}}"

- name: Update modification date of delivery
  command: find "{{hybris_install}}/" -type f -exec touch {} \;

- name: Create link to use the common config folder
  file:
   src: "{{hybris_config}}"
   dest: "{{hybris_install}}/hybris/config"
   state: link

- name: Edit user right for ant
  file:
   path: "{{hybris_ant}}"
   state: touch
   mode: 0777
  tags:
     build

- name: Plateform customization
  command: "{{hybris_ant}} customize" 
  args:
   chdir: "{{hybris_install}}/hybris/bin/platform/"
  tags:
     build

- name: Building platefrom
  command: "{{hybris_ant}} clean all -DHYBRIS_LOG_DIR={{hybris_logs}}"
  args:
   chdir: "{{hybris_install}}/hybris/bin/platform/"
  tags:
     build

- name: Remove hybris release artifact
  file:
   path: "{{item}}"
   state: absent
  with_items:
   - "{{hybris_home}}/{{hybris_release_zip_name}}"
...