---

## Playbook for installing hybris plateform

- name: Create archive for version {{ version }}
  file:
   path: "{{ hybris_delivery }}"
   state: directory

- name: Copy artifact of version {{ version }} into archive
  copy:
   src: "{{ hybris_repo }}/{{ hybris_release_zip_name }}"
   dest: "{{ hybris_delivery }}"
   
...