---
## Playbook for prerelease
# this playbook should be run for each release

- name: Find old releases older than "{{ optimize_delai }}"
  find: 
    paths: "{{ hybris_home }}/install" 
    age: "{{ optimize_delai }}"
    recurse: no
    file_type: directory
    age_stamp: ctime
  register: old_releases
  

- name: Remove old release older than "{{ optimize_delai }}"
  file:
   path: "{{ item.path }}"
   state: absent
  when: old_releases.matched != 0
  with_items: "{{ old_releases.files }}"  
   
...